name: 'Podcast Generator'
author: 'Aleena Jomy'
description: 'Generate a feed for a podcast from a YAML file'
branding:
  icon: 'git-branch'
  color: 'red'
inputs:
  email:
    description: The committer's email address
    required: true
    default: "${{ github.actor }}@localhost"
  name:
    description: Committer's name
    required: true
    default: "${{ github.actor }}@localhost"
run:
  using: 'docker'
  image: 'Dockerfile'
